=== ZhangQiao12580/ProjectDesign/XML实验/XML/schem1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"  attributeFormDefault="unqualified">
	<xs:element name="Orders" type="orders" />
	
	<xs:complexType name="orderdetail">
		
			<xs:sequence>
				
					<xs:element name="name" type="xs:string"/>
					
					<xs:element name="number">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="120"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					
					<xs:element name="city" type="xs:string"/>
					
					<xs:element name="zip">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				
			</xs:sequence>
			
		<xs:attribute name="orderDate" type="xs:date"/>
					<xs:attribute name="orderId">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="A[0-9][0-9][0-9]"/>
							</xs:restriction>
					</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="orders">
		<xs:sequence>
		
			<xs:element name="Order" minOccurs="1" maxOccurs="unbounded" type="orderdetail">
			
			</xs:element>
			
		</xs:sequence>
		
		
		
		
	</xs:complexType>
					
	
	
	
</xs:schema>

=== ZhangQiao12580/ProjectDesign/XML实验/XML/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<Orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/XML1240/XML%e5%ae%9e%e9%aa%8c/schem1.xsd">
	<Order orderId="A001" orderDate="2009-01-20">
		<name>玩具</name>
		<number>10</number>
		<city>北京</city>
		<zip>10000</zip>
	</Order>
	<Order orderId="A002" orderDate="2009-03-20">
		<name>文具</name>
		<number>5</number>
		<city>青岛</city>
		<zip>26000</zip>
	</Order>
</Orders>
